spring:
  application:
    name: coding-challenge
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myDB;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin
  liquibase:
    enabled: true
    user: admin
    password: admin
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console

logging:
  level:
    org:
      springframework:
        web: INFO